// Mandated by FR-5: Search.Notebooks and FR-7: Add.Notebook

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import JoinController from "./join_controller.js"
application.register("join", JoinController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import Dropdown from "stimulus-dropdown";
application.register("dropdown", Dropdown);