# TODO: Implement ideas from here
# TODO: For some reason this is failing in the ci/cd environment
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'gemfiles/vendor/bundle/**/*'

# TODO: Comeback and make these more strict
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false