@startuml Change Password
Title Change Password
|UI|
start
:User is presented new password form;
repeat
  :User enters email;
  :Clicks change password;
  |Domain|
  ::PasswordsController
  create(email);
  |DB|
  :Get user with email;
  |Domain|
  backward :Create error message;
repeat while (User with email exists?) is (false)
->true;
::PasswordsController
generate_random_reset_token();
|DB|
:Save reset token to database;
|Domain|
::PasswordsController
send_reset_password_email();
|UI|
fork
  :Display password reset email sent;
|Domain|
fork again
  :Send password reset email;
|UI|
end fork
:User clicks password reset link in email\n and is presented password reset form;
:User enters a new password and clicks submit;
|Domain|
::PasswordsController
update(email, reset_token, password);
|DB|
:Save user with updated password in database;
|UI|
:Redirect to login page;
stop
@enduml