@startuml Change Password
title Change Password
skinparam sequenceMessageAlign center

actor User as user
participant PasswordsController as pc
participant User as um
database Database as db
database "Email Delivery Platform" as email

user -> pc : new()
activate pc
user <-- pc : render new password form
deactivate pc

user -> pc : create(email)
activate pc
pc -> um : find_by_email(email)
activate um
um -> db : get user by email
activate db
um <-- db : return user
deactivate db
pc <-- um : return user
deactivate um
pc -> pc : generate random reset_token
pc -> um : set_request_new_password(reset_token)
activate um
pc <-- um : return
deactivate um
pc -> um : save()
um -> db : save user to database
pc -> email : send email to reset password
deactivate pc
activate email
user <-- email : send email to user
deactivate email
user -> user : follow link in email
user -> pc : edit()
activate pc
user <-- pc : render edit password form
deactivate pc
user -> pc : update(email, reset_token)
activate pc
pc -> um : find_by_email(email)
activate um
um -> db : get user by email
activate db
um <-- db : return user
deactivate db
pc <-- um : return user
deactivate um
pc -> um : set_password(password)
activate um
pc <-- um : return
deactivate um
pc -> um : save()
um -> db : save user to database

user <- pc : redirect to login page
deactivate pc
@enduml