@startuml Export PDF
title Export PDF
skinparam sequenceMessageAlign center

legend top
User has logged in and is viewing notebooks on dashboard.
endlegend

actor User as user
participant NotebooksController as nc
participant ExportPDFJob as job
participant UsernNotebook as unm
queue Redis as q
participant Sidekiq as kiq
database Database as db

user -> user : select notebook to \nexport and press \nbutton
user -> nc : export(notebook)
nc -> job : perform_later(notebook)
job -> q : enqueue job to be performed later
user <-- job : redirect user to dashboard
q <- kiq : retreive job from queue
q --> kiq : return job
job <- kiq : perform(notebook)
job -> unm : find(notebook, current_user)
unm -> db : get user_notebook by notebook and user
unm <-- db : return user_notebook
job <-- unm : return user_notebook
job -> job : generate_new_pdf_export()
job -> unm : add_pdf_export(pdf_export)
job -> unm : save()
unm -> db : save notebook to database

@enduml