@startuml User Opens a Notebook
title User Opens a Notebook
skinparam sequenceMessageAlign center
legend top
User has logged in and is at the NotebooksController view which displays notebooks.
endlegend

actor User as user
participant NotebooksController as nc
participant Notebook as n
database Database as db

user -> nc : show(notebook)
activate nc
nc -> n : find(notebook_id)
activate n
n -> db : get notebook by id
activate db
db --> n : return notebook
deactivate db
n --> nc : return notebook
deactivate n
nc --> user : return Notebook view which displays a Notebook
deactivate nc
@enduml