@startuml Owner Create Notebook
title User Login & Display Notebooks
skinparam sequenceMessageAlign center

actor User as user
participant NotebooksController as nc
participant User as um
participant User_Notebook as unm
database Database as db

user -> nc : index()
nc -> unm : find_owned_by_user_id(current_user)
unm -> db : get user_notebooks by id
unm <-- db : return user_notebooks
nc <-- unm : return user_notebooks owned by current user
nc -> unm : find_joined_by_user_id(current_user)
unm -> db : get user_notebooks by id
unm <-- db : return user_notebooks
nc <-- unm : return user_notebooks joined by current user
user <-- nc : return NotebooksController view which displays Notebooks

user -> nc: new()

@enduml