@startuml Notebook Participant Selecting and Deleting
title Notebook Participant Selecting and Deleting Diffs
skinparam sequenceMessageAlign center
legend top
Participant has logged in and opened a notebook and there are existing diffs on the participant's Layer.
endlegend

actor Participant as partic
participant NotebookComponent as nc
participant LayerComponent as lc
participant PaperJs as pjs
participant LayerChannel as lch
participant Diff as d
database Database as db

partic -> nc : selects selection tool
activate nc
nc -> nc : setActiveTool("select")
deactivate nc
partic -> lc : draws selection box on canvas
activate lc

lc -> pjs : onMouseDown()
lc -> pjs : onMouseDrag()
lc -> pjs : onMouseUp()
activate pjs
loop for each diff contained by selection box
  pjs -> pjs : set path as fully selected
deactivate pjs
deactivate lc
end

partic -> lc : participant clicks delete key
activate lc

lc -> pjs : onKeyDown()

lc --> partic : render changes
deactivate lc

pjs -> lc : transmitDiff(delete_diff)
activate lc

lc -> lch : send(delete_diff)
deactivate lc
activate lch
lch -> d : new(delete_diff_data)
activate d
d --> lch : return delete_diff
deactivate d
lch -> d : save()
d -> db : save delete_diff to database
lch -> d : find(diff_ids)
activate d
d -> db : get diffs to mark as invisibile by id
activate db
db --> d : return diffs
deactivate db
d --> lch : return diffs
deactivate d
lch -> d : mark_invisible(diff_ids)
loop for each diff_id in diff_ids
  d -> db : save updated diff with diff_id in database
end
deactivate lch

lch -> lc : received(delete_diff)
activate lc
lc -> lc : ignore echoed diff
deactivate lc

@enduml