@startuml Notebook Participant Erasing Diffs
title Notebook Participant Erasing Diffs
skinparam sequenceMessageAlign center
legend top
Participant has logged in and opened a notebook and there are existing diffs on the participant's Layer.
endlegend

actor Participant as partic
participant NotebookComponent as nc
participant LayerComponent as lc
participant PaperJs as pjs
participant LayerChannel as lch
participant Diff as d
database Database as db

partic -> nc : selects eraser tool
activate nc
nc -> nc : setActiveTool("eraser")
deactivate nc
partic -> lc : draws on canvas
activate lc

lc -> pjs : onMouseDown()
lc -> pjs : onMouseDrag()
lc -> pjs : onMouseUp()
activate pjs
pjs -> pjs : layer.remove(intersecting_diffs)
deactivate pjs
deactivate lc
pjs -> lc : transmitDiff(diff)
activate lc

lc --> partic : render changes

lc -> lch : send(updated_diff)
deactivate lc
activate lch
lch -> d : find(diff_id)
activate d
d -> db : get diff by id
activate db
db --> d : return selected_diff
deactivate db
d --> lch : return selected_diff
deactivate d
lch -> d : mark_invisible(selected_diff)
d -> db : save selected_diff marked as invisible to database
deactivate lch

lch -> lc : received(updated_diff)
activate lc
lc -> lc : ignore echoed diff
deactivate lc
@enduml