@startuml Notebook Participant Creating Diffs
title Notebook Participant Creating Diffs
skinparam sequenceMessageAlign center
legend top
Participant has logged in and opened a notebook.
endlegend

actor Participant as partic
participant NotebookComponent as nc
participant LayerComponent as lc
participant PaperJs as pjs
participant LayerChannel as lch
participant Diff as d
database Database as db

partic -> nc : selects pen tool
nc -> nc : setActiveTool("pen")
partic -> nc : select red for tool color
nc -> nc : setActiveColor("red")
partic -> lc : draws on canvas

lc -> pjs : onMouseDown()
lc -> pjs : onMouseDrag()
lc -> pjs : onMouseUp()
pjs -> lc : transmitDiff(diff)

lc --> partic : render drawing
lc -> lch : send(diff)
lch -> d : new(data)
d --> lch : return diff
lch -> d : save()
d -> db : save diff to database
lch -> lc : received(diff)
lc -> lc : ignore echoed diff

@enduml