@startuml Participant Add Notebook
title Participant Add Notebook
skinparam sequenceMessageAlign center

legend top
Participant has logged in and is at the NotebooksController view which displays notebooks.
endlegend

actor Participant as partic
participant NotebooksController as nc
participant Notebook as nm
participant Page as pm
participant Layer as lm
participant User_Notebook as unm
database Database as db

partic -> nc: preview()
partic <-- nc : render preview notebook form
partic -> nc : join(notebook)
nc -> nm : find(notebook_id)
nm -> db : get notebook by id
db --> nm : return notebook
nm --> nc : return notebook
nc -> unm : new(current_user, notebook, is_owner=false)
nc <-- unm : return user_notebook
nc -> nm : set_user_notebooks(user_notebook)
loop for each page i in resource file
    nc -> lm : new(page_i, user_notebook)
    nc <-- lm : return layer_i
    nc -> pm : set_layers(layer_i)
    nc -> nm : set_pages(page_i)
end
nc -> nm : save()
nm -> db : save notebook to database

partic <- nc : display successful join notebook message

@enduml