@startuml Notebook Participant Selecting and Moving
title Notebook Participant Selecting and Moving Diffs
skinparam sequenceMessageAlign center
legend top
Participant has logged in and opened a notebook and there are existing diffs on the participant's Layer.
endlegend

actor Participant as partic
participant NotebookComponent as nc
participant LayerComponent as lc
participant PaperJs as pjs
participant LayerChannel as lch
participant Diff as d
database Database as db

partic -> nc : selects eraser tool
activate nc
nc -> nc : setActiveTool("select")
deactivate nc
partic -> lc : draws selection box on canvas
activate lc
lc -> pjs : onMouseDown()
lc -> pjs : onMouseDrag()
lc -> pjs : onMouseUp()
deactivate lc
loop for each diff contained by selection box
  pjs -> pjs : set path as fully selected
end

partic -> lc : drags and drops diffs elsewhere
activate lc
lc -> pjs : onMouseDown()
lc -> pjs : onMouseDrag()
lc -> pjs : onMouseUp()
lc --> partic : render changes
deactivate lc

pjs -> lc : transmitDiff(move_diff)
activate lc
lc -> lch : send(move_diff)
deactivate lc
activate lch
lch -> d : new(move_diff_data)
activate d
d --> lch : return move_diff
deactivate d
lch -> d : save()
d -> db : save move_diff to database
lch -> d : find(diff_ids)
activate d
d -> db : get diffs to apply offset to by id
activate db
db --> d : return diffs
deactivate db
d --> lch : return diffs
deactivate d
lch -> d : apply_offset(diff_ids, offset)
loop for each diff_id in diff_ids
  d -> db : save updated diff with diff_id in database
end

deactivate lch
lch -> lc : received(move_diff)
activate lc
lc -> lc : ignore echoed diff
deactivate lc

@enduml