name: Rails - Install dependencies, run linters, and run tests

# TODO: Don't let each of the steps fail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      # Basic setup
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Add or Replace any other security checks below here
      - name: Run bundler-audit
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit check

      - name: Run brakeman
        run: |
          bundle exec brakeman -q -w2

      # Add or Replace any other Linters below here
      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel

      # Add or Replace any other tests below here
      - name: Run unit & integration tests
        continue-on-error: true
        run: |
          bin/rails test

      - name: Run system tests
        continue-on-error: true
        run: |
          bin/rails test:system